from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import Qsci

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 599)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.textEdit = Qsci.QsciScintilla(self.centralwidget)
        self.textEdit.setToolTip("")
        self.textEdit.setWhatsThis("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.widget = QtWidgets.QWidget(self.centralwidget)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())

        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(674, 100))
        self.widget.setObjectName("widget")

        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 406, 106))
        self.layoutWidget.setObjectName("layoutWidget")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setText("")

        icon = QtGui.QIcon.fromTheme("window-close")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")

        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")

        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")

        self.horizontalLayout_3.addWidget(self.checkBox)

        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)

        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)

        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 27))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")

        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")

        self.menuChange_Language = QtWidgets.QMenu(self.menuView)
        self.menuChange_Language.setObjectName("menuChange_Language")

        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        MainWindow.setMenuBar(self.menubar)

        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")

        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)

        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_As.setIcon(icon)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-cut")
        self.actionCut.setIcon(icon)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.actionCopy.setIcon(icon)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-paste")
        self.actionPaste.setIcon(icon)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-undo")
        self.actionUndo.setIcon(icon)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-redo")
        self.actionRedo.setIcon(icon)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-select-all")
        self.actionSelect_All.setIcon(icon)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.actionWordwrap = QtWidgets.QAction(MainWindow)
        self.actionWordwrap.setCheckable(True)
        self.actionWordwrap.setChecked(True)
        self.actionWordwrap.setObjectName("actionWordwrap")

        self.actionEnlarge = QtWidgets.QAction(MainWindow)
        self.actionEnlarge.setObjectName("actionEnlarge")

        self.actionShrink_Font = QtWidgets.QAction(MainWindow)
        self.actionShrink_Font.setObjectName("actionShrink_Font")

        self.actionShow_line_numbers = QtWidgets.QAction(MainWindow)
        self.actionShow_line_numbers.setCheckable(True)
        self.actionShow_line_numbers.setChecked(True)
        self.actionShow_line_numbers.setObjectName("actionShow_line_numbers")

        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")

        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")

        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")

        self.actionNormal = QtWidgets.QAction(MainWindow)
        self.actionNormal.setObjectName("actionNormal")
        self.actionBatch = QtWidgets.QAction(MainWindow)

        self.actionBatch.setObjectName("actionBatch")
        self.actionCmake = QtWidgets.QAction(MainWindow)
        self.actionCmake.setObjectName("actionCmake")
        self.actionCoffeeScript = QtWidgets.QAction(MainWindow)
        self.actionCoffeeScript.setObjectName("actionCoffeeScript")
        self.actionC = QtWidgets.QAction(MainWindow)
        self.actionC.setObjectName("actionC")
        self.actionC_2 = QtWidgets.QAction(MainWindow)
        self.actionC_2.setObjectName("actionC_2")
        self.actionC_3 = QtWidgets.QAction(MainWindow)
        self.actionC_3.setObjectName("actionC_3")
        self.actionCSS = QtWidgets.QAction(MainWindow)
        self.actionCSS.setObjectName("actionCSS")
        self.actionFortan = QtWidgets.QAction(MainWindow)
        self.actionFortan.setObjectName("actionFortan")
        self.actionHTML = QtWidgets.QAction(MainWindow)
        self.actionHTML.setObjectName("actionHTML")
        self.actionJSON = QtWidgets.QAction(MainWindow)
        self.actionJSON.setObjectName("actionJSON")
        self.actionMakeFIle = QtWidgets.QAction(MainWindow)
        self.actionMakeFIle.setObjectName("actionMakeFIle")
        self.actionMarkDown = QtWidgets.QAction(MainWindow)
        self.actionMarkDown.setObjectName("actionMarkDown")
        self.actionMat = QtWidgets.QAction(MainWindow)
        self.actionMat.setObjectName("actionMat")
        self.actionPascal = QtWidgets.QAction(MainWindow)
        self.actionPascal.setObjectName("actionPascal")
        self.actionPerl = QtWidgets.QAction(MainWindow)
        self.actionPerl.setObjectName("actionPerl")
        self.actionPython = QtWidgets.QAction(MainWindow)
        self.actionPython.setObjectName("actionPython")
        self.actionRuby = QtWidgets.QAction(MainWindow)
        self.actionRuby.setObjectName("actionRuby")
        self.actionSQL = QtWidgets.QAction(MainWindow)
        self.actionSQL.setObjectName("actionSQL")
        self.actionXML = QtWidgets.QAction(MainWindow)
        self.actionXML.setObjectName("actionXML")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtWidgets.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionChange_Font = QtWidgets.QAction(MainWindow)
        self.actionChange_Font.setObjectName("actionChange_Font")
        self.actionchange_font_color = QtWidgets.QAction(MainWindow)
        self.actionchange_font_color.setObjectName("actionchange_font_color")
        self.actionclose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-close")
        self.actionclose.setIcon(icon)
        self.actionclose.setObjectName("actionclose")
        self.actionDeselect = QtWidgets.QAction(MainWindow)
        self.actionDeselect.setObjectName("actionDeselect")
        self.actionstatus_bar = QtWidgets.QAction(MainWindow)
        self.actionstatus_bar.setCheckable(True)
        self.actionstatus_bar.setChecked(True)
        self.actionstatus_bar.setObjectName("actionstatus_bar")
        self.actionReplace_2 = QtWidgets.QAction(MainWindow)
        self.actionReplace_2.setObjectName("actionReplace_2")

        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionclose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionDeselect)
        self.menuChange_Language.addAction(self.actionNormal)
        self.menuChange_Language.addAction(self.actionBatch)
        self.menuChange_Language.addAction(self.actionCmake)
        self.menuChange_Language.addAction(self.actionCoffeeScript)
        self.menuChange_Language.addAction(self.actionC)
        self.menuChange_Language.addAction(self.actionC_2)
        self.menuChange_Language.addAction(self.actionC_3)
        self.menuChange_Language.addAction(self.actionCSS)
        self.menuChange_Language.addAction(self.actionFortan)
        self.menuChange_Language.addAction(self.actionHTML)
        self.menuChange_Language.addAction(self.actionJSON)
        self.menuChange_Language.addAction(self.actionMakeFIle)
        self.menuChange_Language.addAction(self.actionMarkDown)
        self.menuChange_Language.addAction(self.actionMat)
        self.menuChange_Language.addAction(self.actionPascal)
        self.menuChange_Language.addAction(self.actionPerl)
        self.menuChange_Language.addAction(self.actionPython)
        self.menuChange_Language.addAction(self.actionRuby)
        self.menuChange_Language.addAction(self.actionSQL)
        self.menuChange_Language.addAction(self.actionXML)
        self.menuView.addAction(self.actionWordwrap)
        self.menuView.addAction(self.actionEnlarge)
        self.menuView.addAction(self.actionShrink_Font)
        self.menuView.addAction(self.actionShow_line_numbers)
        self.menuView.addAction(self.menuChange_Language.menuAction())
        self.menuView.addAction(self.actionChange_Font)
        self.menuView.addAction(self.actionchange_font_color)
        self.menuView.addAction(self.actionstatus_bar)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionCut.triggered.connect(self.textEdit.cut)
        self.actionCopy.triggered.connect(self.textEdit.copy)
        self.actionPaste.triggered.connect(self.textEdit.paste)
        self.actionSelect_All.triggered.connect(self.textEdit.selectAll)
        self.actionUndo.triggered.connect(self.textEdit.undo)
        self.actionRedo.triggered.connect(self.textEdit.redo)
        self.actionShrink_Font.triggered.connect(self.textEdit.zoomOut)
        self.actionEnlarge.triggered.connect(self.textEdit.zoomIn)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intelligent Code"))
        self.pushButton_2.setText(_translate("MainWindow", "find"))
        self.checkBox.setText(_translate("MainWindow", "regular expression"))
        self.checkBox_2.setText(_translate("MainWindow", "case sensitive"))
        self.checkBox_3.setText(_translate("MainWindow", "whole word"))
        self.pushButton_3.setText(_translate("MainWindow", "Replace"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuChange_Language.setTitle(_translate("MainWindow", "La&nguage"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Sa&ve As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionCut.setText(_translate("MainWindow", "&Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "C&opy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "&Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionSelect_All.setText(_translate("MainWindow", "&Select All"))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionWordwrap.setText(_translate("MainWindow", "&Wordwrap"))
        self.actionEnlarge.setText(_translate("MainWindow", "&Enlarge"))
        self.actionEnlarge.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionShrink_Font.setText(_translate("MainWindow", "&Shrink Font"))
        self.actionShrink_Font.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionShow_line_numbers.setText(_translate("MainWindow", "Show &line numbers"))
        self.actionFind.setText(_translate("MainWindow", "&Find and Replace"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionReplace.setText(_translate("MainWindow", "R&eplace"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionNormal.setText(_translate("MainWindow", "&Normal"))
        self.actionBatch.setText(_translate("MainWindow", "Batch"))
        self.actionCmake.setText(_translate("MainWindow", "&Cmake"))
        self.actionCoffeeScript.setText(_translate("MainWindow", "C&offeeScript"))
        self.actionC.setText(_translate("MainWindow", "C"))
        self.actionC_2.setText(_translate("MainWindow", "C++"))
        self.actionC_3.setText(_translate("MainWindow", "C#"))
        self.actionCSS.setText(_translate("MainWindow", "CSS"))
        self.actionFortan.setText(_translate("MainWindow", "&Fortan"))
        self.actionHTML.setText(_translate("MainWindow", "&HTML"))
        self.actionJSON.setText(_translate("MainWindow", "&JSON"))
        self.actionMakeFIle.setText(_translate("MainWindow", "&MakeFIle"))
        self.actionMarkDown.setText(_translate("MainWindow", "Mar&kDown"))
        self.actionMat.setText(_translate("MainWindow", "Mat"))
        self.actionPascal.setText(_translate("MainWindow", "&Pascal"))
        self.actionPerl.setText(_translate("MainWindow", "P&erl"))
        self.actionPython.setText(_translate("MainWindow", "Python"))
        self.actionRuby.setText(_translate("MainWindow", "&Ruby"))
        self.actionSQL.setText(_translate("MainWindow", "&SQL"))
        self.actionXML.setText(_translate("MainWindow", "&XML"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview"))
        self.actionChange_Font.setText(_translate("MainWindow", "&Change Font"))
        self.actionchange_font_color.setText(_translate("MainWindow", "Change &Font Color"))
        self.actionclose.setText(_translate("MainWindow", "&Close"))
        self.actionclose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionDeselect.setText(_translate("MainWindow", "&Deselect"))
        self.actionstatus_bar.setText(_translate("MainWindow", "show status &bar"))
        self.actionReplace_2.setText(_translate("MainWindow", "Replace"))

